[project]
name = "MaaFw"
version = "0"
requires-python = ">=3.12"
authors = [{ name = "MaaXYZ" }]
description = "An automation black-box testing framework based on image recognition"
readme = "README.md"
urls = { Homepage = "https://github.com/MaaXYZ/MaaFramework" }
dependencies = ["numpy", "MaaAgentBinary"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["maa"]
