blank_issues_enabled: false
contact_links:
    - name: ğŸ“– é—®é¢˜åé¦ˆæŒ‡å— / Troubleshooting Guide
      url: https://github.com/MaaXYZ/MaaFramework/blob/main/docs/zh_cn/5.1-é—®é¢˜åé¦ˆ.md
      about: æäº¤ Issue å‰è¯·å…ˆé˜…è¯»æ­¤æ–‡æ¡£ / Please read this guide before submitting an issue
    - name: ğŸ§ QQ ç¾¤ / QQ Group (595990173)
      url: https://qm.qq.com/q/RzN0wJlPQO
      about: ä»…è®¨è®ºå¼€å‘ç›¸å…³è®®é¢˜ / Development discussions only
