[package]
name = "maa-framework"
version = "0.1.0"
edition = "2021"
authors = ["MaaFramework Contributors"]
description = "Rust bindings for MaaFramework"
license = "MIT"
repository = "https://github.com/MaaAssistantArknights/MaaFramework"
keywords = ["maa", "automation", "framework", "binding"]
categories = ["api-bindings", "development-tools"]

[dependencies]
derive_builder = "0.20.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"

thiserror = "^1.0"

log = "0.4"
bitflags = "2.4"
image = { version = "0.25", optional = true }

[build-dependencies]
bindgen = "0.69.4"

[features]
default = ["toolkit", "adb", "win32", "dbg", "custom", "internal"]
toolkit = []
adb = []
win32 = []
dbg = []
custom = [
    "custom_recognizer",
    "custom_controller",
    "custom_action",
    "sync_context",
]
custom_recognizer = ["sync_context"]
custom_controller = ["sync_context"]
custom_action = ["sync_context"]
sync_context = []
internal = []
image = ["dep:image"]
