name: mirrorchyan_release_note

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false
  release:
    types: [edited]

jobs:
    mirrorchyan:
        if: ${{ github.repository_owner == 'MaaXYZ' }}
        runs-on: macos-latest

        steps:
            - id: uploading
              uses: MirrorChyan/release-note-action@v1
              with:
                  mirrorchyan_rid: MaaFramework
                  version_name: ${{ inputs.tag }}

                  owner: MaaXYZ
                  repo: MaaFramework
                  upload_token: ${{ secrets.MirrorChyanUploadToken }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
